### ISSUE TITLE
Providing a Single Question Based on Filters

### ISSUE THREAD

**Issue by songfangyl** [CS3219-AY2425S1/cs3219-ay2425s1-project-g12#25]
Description: The system should provide a single question selected from a set of questions that match specific criteria (e.g., category, difficulty).
Acceptance Criteria:
If multiple questions meet the criteria, the system should randomly select one from the matching set.
The returned question must have details such as title, description, category, difficulty and image (if needed).

**Comment by lyuanww** [comment]
Closed due to changed requirements

We are using user's selection of questions instead of randomisation
