### ISSUE TITLE
Frontend fixes

### ISSUE THREAD

**Issue by LamJiuFong** [CS3219-AY2425S1/cs3219-ay2425s1-project-g12#40]
- [ ] render list of categories
- [ ] add link field to question form
- [ ] add examples field to question form
- [ ] add hint field to question form
- [ ] implement api calls to get/post categories (if we want to follow the old schema)
- [ ]  get question by title flow?

Feel free to comment/tick if any changes is unnecessary

**Comment by jingting1412** [comment]
- [ ] Add dropdown menu for selecting categories to questionForm after adding way to add/update/delete categories
- [ ] Change how question complexity is displayed
- [ ] Revamp login/signup page
- [ ] Revamp Home page

some additional things I think we can do to the pages we have now
